



spring:
  application:
    name: review-microservice

  datasource:
    url: jdbc:mysql://localhost:3306/reviewDb?createDatabaseIfNotExist=true
    username: root
    password: HA1256ri#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Recommended for MySQL 8

server:
  port: 9002

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
    register-with-eureka: true
    fetch-registry: true
