#server:
#  port: 8088
#
#spring:
#  application:
#    name: eureka-server
#
#eureka:
#  instance:
#    hostname: localhost
#
#  client:
#    fetch-registry: false
#    register-with-eureka: false

server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}

  client:
    fetch-registry: false
    register-with-eureka: false












