#spring.application.name=service-offering
#
#
#server.port=8085
#
#
##mysql configuration
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/saloonServiceDB
#spring.datasource.username=root
#spring.datasource.password=HA1256ri#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true


spring:
  application:
    name: service-offering

  datasource:
    url: jdbc:mysql://localhost:3306/saloonServiceDB?createDatabaseIfNotExist=true
    username: root
    password: HA1256ri#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Recommended for MySQL 8

server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: "http://localhost:8088/eureka/"
    register-with-eureka: true
    fetch-registry: true
