#spring.application.name=paymentMicroservice
#
#
#server.port=8087
#
#
##mysql configuration
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/paymentDB
#spring.datasource.username=root
#spring.datasource.password=HA1256ri#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
#
#
#razorpay.api.key="key"
#razorpay.api.secret="scert"
#
#
#stripe.api.key="key"

spring:
  application:
    name: payment-microservice

  datasource:
    url: jdbc:mysql://localhost:3306/paymentDB?createDatabaseIfNotExist=true
    username: root
    password: HA1256ri#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest

server:
  port: 8087

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: "http://localhost:8088/eureka/"

#razorpay:
#  api:
#    key: "rzp_test_us_1kARZSA09Qu4CB"
#    secret: "p8Euasu4euFDUWw57JiE6bgm"
#
#stripe:
#  api:
#    publishable: "pk_test_51RxXncGelJ4HBHnI9cVvQ6mcRq9dyB438BCOAOjzB8OKjA6iOBJrk4G392zkcVZJRDS4DVaga4jbDWKyqe5U9fPi00olStqVmH"
#    secret: ""
