#
#
#spring:
#  application:
#    name: payment-microservice
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/paymentDB?createDatabaseIfNotExist=true
#    username: root
#    password: HA1256ri#
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  rabbitmq:
#    port: 5672
#    host: localhost
#    username: guest
#    password: guest
#
#server:
#  port: 8087
#
#eureka:
#  instance:
#    prefer-ip-address: true
#
#  client:
#    service-url:
#      defaultZone: "http://localhost:8088/eureka/"
#razorpay:
#  api:
#    key: ${RAZORPAY_API_KEY}
#    secret: ${RAZORPAY_API_SECRET}
#
#stripe:
#  api:
#    publishable: ${STRIPE_API_PUBLISHABLE}
#    secret: ${STRIPE_API_SECRET}


spring:
  application:
    name: payment-microservice

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/paymentdb?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:HA1256ri#}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

server:
  port: ${SERVER_PORT:8087}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8088/eureka/}

razorpay:
  api:
    key: ${RAZORPAY_API_KEY}
    secret: ${RAZORPAY_API_SECRET}

stripe:
  api:
    publishable: ${STRIPE_API_PUBLISHABLE}
    secret: ${STRIPE_API_SECRET}

